# Generated by Django 5.0.4 on 2024-04-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Credentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("email", models.EmailField(default="email", max_length=254)),
                ("username", models.CharField(default="username", max_length=50)),
                ("password", models.CharField(default="password", max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
